figure()
subplot(3,1,1)
periodogram(u,'power');
ylabel("Power (dB)",...
        'Interpreter','Latex')
xlabel("Normalized frequency ($\times\pi$ rad/sample)",...
        'Interpreter','Latex')
title("Power spectral density estimate for $u(t)$",...
        'Interpreter','Latex')
subplot(3,1,2)
periodogram(e,'power');
xlabel("Normalized frequency ($\times\pi$ rad/sample)",...
        'Interpreter','Latex')
title("Power spectral density estimate for $e(t)$",...
        'Interpreter','Latex')
ylabel("Power (dB)",...
        'Interpreter','Latex')
e_prior = [0 e(1:end-1)];
subplot(3,1,3)
periodogram(e+e_prior,'power');
ylabel("Power (dB)",...
        'Interpreter','Latex')
title("Power spectral density estimate for $z(t)$",...
        'Interpreter','Latex')
xlabel("Normalized frequency ($\times\pi$ rad/sample)",...
        'Interpreter','Latex')